[nexus.registry]
endpoints    = ["127.0.0.1:2379"]
dial_timeout = 5
lease_ttl    = 15
prefix       = "/nexus/services"

[nexus.service]
name     = "user-service"
version  = "v1.0.0"
protocol = "http"
address  = "10.0.0.1:8080"
weight   = 10

[nexus.service.metadata]
region = "ap-northeast-1"
env    = "production"
